# Challenge 3: Music Genre Classification - Feature Engineering

### Khai báo thư viện

In [1]:
import pandas as pd
import os
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from IPython.display import display

import warnings
%matplotlib inline
warnings.filterwarnings("ignore")

In [2]:
# params
seed = 42 

exps_dir = "../exps"
if os.path.exists(exps_dir) == False:
  os.makedirs(exps_dir, exist_ok=True)

save_dir = f"{exps_dir}/feature1"
os.makedirs(save_dir, exist_ok=True)

data_path = "../exps/data"

### Đọc dữ liệu

In [3]:
# Đọc dữ liệu gốc
df_train_org = pd.read_csv("../../data03/train.csv")
df_test_org = pd.read_csv("../../data03/test.csv")

# Đọc dữ liệu đã preprocessing
df_train_pre = pd.read_excel(f"{data_path}/train.xlsx")
df_test_pre  = pd.read_excel(f"{data_path}/test.xlsx")

print("Kích thước dữ liệu:")
print("Train:", df_train_org.shape)
print("Test:", df_test_org.shape)

df_train_org.head()

Kích thước dữ liệu:
Train: (14396, 18)
Test: (3600, 17)

,Id,Artist Name,Track Name,Popularity,danceability,energy,key,loudness,mode,speechiness,acousticness,instrumentalness,liveness,valence,tempo,duration_in min/ms,time_signature,Class
0,1,Marina Maximilian,Not Afraid,37.0,0.334,0.536,9.0,-6.649,0,0.0381,0.378000,NaN,0.106,0.235,152.429,204947.0,4,9
1,2,The Black Keys,Howlin' for You,67.0,0.725,0.747,11.0,-5.545,1,0.0876,0.027200,0.0468,0.104,0.380,132.921,191956.0,4,6
2,3,Royal & the Serpent,phuck u,NaN,0.584,0.804,7.0,-6.094,1,0.0619,0.000968,0.6350,0.284,0.635,159.953,161037.0,4,10
3,4,Detroit Blues Band,Missing You,12.0,0.515,0.308,NaN,-14.711,1,0.0312,0.907000,0.0213,0.300,0.501,172.472,298093.0,3,2
4,5,Coast Contra,My Lady,48.0,0.565,0.777,6.0,-5.096,0,0.2490,0.183000,NaN,0.211,0.619,88.311,254145.0,4,5

### Tách target + gộp train/test để FE đồng nhất

In [4]:
# Tách target
y = df_train_org["Class"].copy()

train = df_train_org.drop(columns=["Class"])
test  = df_test_org.copy()

print("Train no target:", train.shape)
print("Test:", test.shape)

# Gộp để feature engineering nhất quán
all_df = pd.concat([train, test], ignore_index=True)
print("All shape:", all_df.shape)

Train no target: (14396, 17)
Test: (3600, 17)
All shape: (17996, 17)

FE ...

### Tách lại train/test sau FE

In [5]:
train_fe = all_df.iloc[:len(train)].copy()
test_fe  = all_df.iloc[len(train):].copy()

train_fe["SalePrice"] = y.values

print("Train FE:", train_fe.shape)
print("Test FE :", test_fe.shape)

train_fe.head()

Train FE: (14396, 18)
Test FE : (3600, 17)

,Id,Artist Name,Track Name,Popularity,danceability,energy,key,loudness,mode,speechiness,acousticness,instrumentalness,liveness,valence,tempo,duration_in min/ms,time_signature,SalePrice
0,1,Marina Maximilian,Not Afraid,37.0,0.334,0.536,9.0,-6.649,0,0.0381,0.378000,NaN,0.106,0.235,152.429,204947.0,4,9
1,2,The Black Keys,Howlin' for You,67.0,0.725,0.747,11.0,-5.545,1,0.0876,0.027200,0.0468,0.104,0.380,132.921,191956.0,4,6
2,3,Royal & the Serpent,phuck u,NaN,0.584,0.804,7.0,-6.094,1,0.0619,0.000968,0.6350,0.284,0.635,159.953,161037.0,4,10
3,4,Detroit Blues Band,Missing You,12.0,0.515,0.308,NaN,-14.711,1,0.0312,0.907000,0.0213,0.300,0.501,172.472,298093.0,3,2
4,5,Coast Contra,My Lady,48.0,0.565,0.777,6.0,-5.096,0,0.2490,0.183000,NaN,0.211,0.619,88.311,254145.0,4,5

In [6]:
# Lưu file FE 
train_fe.to_excel(f"{data_path}/train_fe.xlsx", index=False)
test_fe.to_excel(f"{data_path}/test_fe.xlsx", index=False)

print("Saved:")
print(f"{data_path}/train_fe.xlsx")
print(f"{data_path}/test_fe.xlsx")

Saved:
../exps/data/train_fe.xlsx
../exps/data/test_fe.xlsx